name=input('Enter a name: ')
age=int(input('Enter a age: '))
height=float(input('Enter a height'))
weight=float(input('Enter a Weight'))
vote=bool(input('Eligible to vote True or False'))
course=input("Enter a course name")
phone=int(input("Enter a phone no."))
city=input("Enter a city: ")
vehical=input("Enter a vehical type")
v_model=input("Enter a vehical model")
print('-----------')

print("Name: ",name)
print('age: ',age)
print('height: ',height)
print('weight: ',weight)
print('vote: ',vote)
print('course: ',course)
print('phone: ',phone)
print('city: ',city)
print('vehical type: ',vehical)
print('vehical model: ',v_model)
